# Generated by Django 4.1.2 on 2023-08-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_confirm_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
